version: '3.8'

services:
  gfrom-backend:
    container_name: google-form-api
    image: mayukhdev2000/gfrom-backend:latest  # Use pulled image instead of build
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - CONNECTION_URL=mongodb+srv://dasmayukh2000:936eIP2SWazsX5Pp@cluster0.93aiybh.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - gform-mongodb
    networks:
      - app-network

  gform-frontend:
    container_name: google-form-ui
    image: mayukhdev2000/gfrom-frontend:latest  # Use pulled image instead of build
    ports:
      - "3000:5173"
    depends_on:
      - gfrom-backend
    networks:
      - app-network

  gform-mongodb:
    container_name: google-form-mongo
    image: mayukhdev2000/gfrom-mongodb:latest
    ports:
      - "6000:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge